# Generated by Django 5.2.6 on 2025-10-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solar',
            fields=[
                ('solarId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('load', models.IntegerField()),
            ],
        ),
    ]
