# Generated by Django 5.2.6 on 2025-10-18 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solar',
            fields=[
                ('solarId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('load', models.IntegerField(default=0)),
                ('gridStatus', models.BooleanField(default=False)),
                ('solarValue', models.IntegerField(default=0)),
                ('isBateryFull', models.BooleanField(default=False)),
                ('batteryValue', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
