# Generated by Django 5.2.6 on 2025-10-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_solar_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('confId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('invertorCapacity', models.IntegerField(default=0)),
                ('instaledSolarPower', models.IntegerField(default=0)),
                ('batteryCapacity', models.IntegerField(default=0)),
            ],
        ),
    ]
