# Generated by Django 5.2.6 on 2025-10-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_solar_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='solar',
            name='gridStatus',
            field=models.BooleanField(default=False),
        ),
    ]
