# Generated by Django 5.2.6 on 2025-10-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_solar_gridstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='solar',
            name='solarValue',
            field=models.IntegerField(default=0),
        ),
    ]
