# Generated by Django 5.2.6 on 2025-10-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_configuration_user_alter_solar_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='solar',
            name='batteryCapacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solar',
            name='instaledSolarPower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solar',
            name='invertorCapacity',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Configuration',
        ),
    ]
