# Generated by Django 5.2.7 on 2025-10-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_solar_batterycapacity_solar_instaledsolarpower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solar',
            name='batteryPrecent',
            field=models.IntegerField(default=False),
        ),
    ]
