# Generated by Django 5.2.7 on 2025-10-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_solar_batteryprecent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solar',
            name='isBateryFull',
        ),
        migrations.AddField(
            model_name='solar',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
