# Generated by Django 5.2.7 on 2025-10-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_solar_isbateryfull_solar_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='solar',
            name='netPower',
            field=models.IntegerField(default=0),
        ),
    ]
