# Generated by Django 5.2.7 on 2025-10-31 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_solar_netpower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solar',
            name='last_update',
        ),
    ]
